name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Instalar dependencias
        run: pnpm install

      - name: Correr tests unitarios
        run: pnpm test:unit --run

      - name: Build de producción
        run: pnpm build

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOCKEN }}

      - name: Build y push imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: bazzty/knight-of-hope:latest
